version: '3.8'

services:
  rainfall-db-dev:
    image: mariadb:latest
    container_name: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: rainfall-dev-db
      MYSQL_DATABASE: rainfall_dev
    ports:
      - "6555:3306"

  minio:
    image: minio/minio
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - ./rainfall-minio:/data
    environment:
      MINIO_ROOT_USER: rainfall
      MINIO_ROOT_PASSWORD: rainfall-minio
    command: server --console-address :9001 /data