# fly.toml app configuration file generated for rainfall on 2023-12-05T20:05:11-08:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "rainfall"
primary_region = "sjc"

[build]

[processes]
  app = "pipenv run gunicorn --error-logfile - --access-logfile - -b 0.0.0.0 rainfall.main:create_app()"
  worker = "pipenv run python -m celery -A rainfall.main worker -l info"

[mounts]
  source="rainfall_data"
  destination="/data"
  processes = ["worker"]

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[vm]]
  cpu_kind = "shared"
  cpus = 2
  memory_mb = 4096
