"""Add netlify_site_id to Site

Revision ID: 03e6e9292a46
Revises: 47f4cef012e7
Create Date: 2024-11-09 09:44:27.338483

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = '03e6e9292a46'
down_revision: Union[str, None] = '47f4cef012e7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
  # ### commands auto generated by Alembic - please adjust! ###
  op.add_column(
      'sites', sa.Column('netlify_site_id',
                         sa.String(length=255),
                         nullable=True))
  # ### end Alembic commands ###


def downgrade() -> None:
  # ### commands auto generated by Alembic - please adjust! ###
  op.drop_column('sites', 'netlify_site_id')
  # ### end Alembic commands ###
