"""Add task id to sites

Revision ID: 20a525107a88
Revises: 3b83d643e6cb
Create Date: 2025-01-06 14:57:01.760943

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '20a525107a88'
down_revision: Union[str, None] = '3b83d643e6cb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sites', sa.Column('preview_task_id', sa.String(length=255), nullable=True))
    op.drop_index('fk_sites_sites_users_id', table_name='sites')
    op.create_foreign_key(None, 'sites', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'sites', type_='foreignkey')
    op.create_index('fk_sites_sites_users_id', 'sites', ['user_id'], unique=False)
    op.drop_column('sites', 'preview_task_id')
    # ### end Alembic commands ###
