"""Add artwork to Release

Revision ID: 3eb712c93cdb
Revises: 15e450676fca
Create Date: 2024-01-28 11:19:20.503725

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3eb712c93cdb'
down_revision: Union[str, None] = '15e450676fca'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('artwork',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('filename', sa.String(length=1024), nullable=False),
    sa.Column('release_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['release_id'], ['releases.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('artwork')
    # ### end Alembic commands ###
