"""Add mastodon id, rename Mastodon token

Revision ID: 5a0902890ee4
Revises: 3604b4c7a42c
Create Date: 2024-01-19 19:08:52.659331

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = '5a0902890ee4'
down_revision: Union[str, None] = '3604b4c7a42c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
  # ### commands auto generated by Alembic - please adjust! ###
  op.add_column('users',
                sa.Column('mastodon_id', sa.String(length=255), nullable=True))
  op.add_column(
      'users',
      sa.Column('mastodon_access_token', sa.String(length=255), nullable=True))
  op.drop_column('users', 'mastodon_auth_token')
  # ### end Alembic commands ###


def downgrade() -> None:
  # ### commands auto generated by Alembic - please adjust! ###
  op.add_column(
      'users',
      sa.Column('mastodon_auth_token', sa.VARCHAR(length=255), nullable=True))
  op.drop_column('users', 'mastodon_access_token')
  op.drop_column('users', 'mastodon_id')
  # ### end Alembic commands ###
