"""Add mastodon_credentials

Revision ID: f0e2ae637ca4
Revises: 9e4bcadf779d
Create Date: 2024-01-17 10:49:40.920382

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f0e2ae637ca4'
down_revision: Union[str, None] = '9e4bcadf779d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mastodon_credentials',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('netloc', sa.String(length=255), nullable=False),
    sa.Column('client_id', sa.String(length=255), nullable=False),
    sa.Column('client_secret', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('mastodon_credentials')
    # ### end Alembic commands ###
